#!/usr/bin/env python3
import argparse
import os
import shutil
import socket

from utils import tools


class BountyHunter:
    def __init__(self, name: str, remote_ip: str):
        self.name = tools.sanitize_file_name(file=name)
        self.remote_ip = tools.sanitize_ipv4(ip=remote_ip)

        self.home = os.environ['HOME']
        self.cwd = os.getcwd()

        self.source_directory = os.path.abspath(os.path.dirname(__file__))
        self.destination_directory = os.path.abspath(self.name)

        self.md_files = list()
        self.local_ip = str()

    def copy_dir_template(self):
        """
        Copy 'dir_template' to the new destination.
        """

        dir_template_path = os.path.abspath(f"{self.source_directory}/dir_template")
        shutil.copytree(dir_template_path, self.destination_directory)
        return f"The 'dir_template' has successful been copied to '{self.destination_directory}'."

    def find_md_files(self):
        extensions = [
            '.md',
            '.sh'
        ]
        for root, dirs, files in os.walk(self.destination_directory):
            for file in files:
                filename, file_extension = os.path.splitext(file)
                if file_extension in extensions:
                    self.md_files.append(f"{root}/{file}")

        return self.md_files

    def get_local_ip(self):
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect((self.remote_ip, 0)) 
        self.local_ip = s.getsockname()[0]
        return self.local_ip

    def replace_template_variables(self):
        for file in self.md_files:
            data = tools.read_file(file=file)
            data = data.replace("{{TARGET}}", f"{self.name.lower()}.htb")
            data = data.replace("{{RHOST}}", f"{self.remote_ip}")
            data = data.replace("{{LHOST}}", f"{self.local_ip}")
            data = data.replace("{{QUICK_DIR}}", f"alias {self.name.lower()}.htb='cd {self.destination_directory}'")
            tools.write_file(file=file, data=data)

    def main(self):
        self.get_local_ip()
        self.copy_dir_template()
        self.find_md_files()
        self.replace_template_variables()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Setup a workspace specifically for HTB.')
    parser.add_argument('-n', '--name', help='Name of HTB machine.', required=True)
    parser.add_argument('-i', '--ip', help='IP Address of HTB machine.', required=True)

    args = parser.parse_args()

    x = BountyHunter(name=args.name, remote_ip=args.ip)
    x.main()
